name: Deploy API to Azure Web App
on:
  push:
    branches: [main]
    paths:
      - 'api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: api } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - name: Publish
        run: dotnet publish -c Release -o out
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mini-health-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api/out
